apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rwy1gbfgo-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rwy1gbfgo-nodejs 
  name: rwy1gbfgo-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rwy1gbfgo-nodejs 
